apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test-swagger"
  description: "This is to test spring boot template"
  annotations:
    github.com/project-slug: Sahana-Nagaraja/test-swagger
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  providesApis:
    - "test-swagger"
  lifecycle: experimental
  owner: "group:default/guests"
